baseurl = "https://financialliteracy.press"
title = "Financial Literacy"
author = "Adit Sachde & Vincent Zhu"
canonifyurls = true
paginate = 3

theme = "hugo-theme-lean-launch-page"

#googleAnalytics = "UA-123456"

[params]
tagline = "Resources to learn financial literacy!"
#mailchimpURL = "//my-account.mailchimp.com/my-subscriber-url"

#twitter = "https://twitter.com/MyNewProduct"
#facebook = "https://facebook.com/MyNewProduct"
#instagram = "https://instagram.com/MyNewProduct"
#googleplus = "https://plus.google.com/+MyNewProduct"
